/**
 * URL safety helpers. Every action rendered on a POC page must pass through
 * one of these. JavaScript URLs, data URLs, and malformed protocols are
 * rejected before they can reach an href.
 */

import { getRuntimeImageHosts } from "./image-hosts";

const SAFE_PROTOCOLS = new Set(["https:"]);

/** True when the URL parses, is absolute, and uses https. */
export function isSafeExternalUrl(raw: string): boolean {
  try {
    const url = new URL(raw);
    return SAFE_PROTOCOLS.has(url.protocol);
  } catch {
    return false;
  }
}

/** Normalizes an https URL, or returns null when unsafe. */
export function safeExternalUrl(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const trimmed = raw.trim();
  if (!isSafeExternalUrl(trimmed)) return null;
  return trimmed;
}

/** Extracts dialable digits and returns a tel: href, or null when unusable. */
export function telHref(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const trimmed = raw.replace(/[^\d+]/g, "");
  const digits = trimmed.replace(/\D/g, "");
  if (digits.length < 7 || digits.length > 15) return null;
  return `tel:${trimmed.startsWith("+") ? "+" : ""}${digits}`;
}

/** Returns a mailto: href for a plausible email, or null. */
export function mailtoHref(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const trimmed = raw.trim();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(trimmed)) return null;
  return `mailto:${trimmed}`;
}

/** Builds a Google Maps search URL from coordinates or an address. */
export function mapsQueryUrl(place: {
  latitude?: number | null;
  longitude?: number | null;
  formattedAddress?: string | null;
}): string | null {
  const { latitude, longitude, formattedAddress } = place;
  if (typeof latitude === "number" && typeof longitude === "number") {
    return `https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`;
  }
  if (formattedAddress) {
    return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedAddress)}`;
  }
  return null;
}

/**
 * Builds a zero-credential Google Maps embed URL. This is intentionally
 * generated by the application instead of accepted as an arbitrary iframe
 * URL from a record. It keeps every POC map useful when no API key or
 * provider-supplied embed URL is available.
 */
export function mapsEmbedUrl(place: {
  latitude?: number | null;
  longitude?: number | null;
  formattedAddress?: string | null;
}): string | null {
  const { latitude, longitude, formattedAddress } = place;
  const query =
    typeof latitude === "number" && typeof longitude === "number"
      ? `${latitude},${longitude}`
      : formattedAddress?.trim();
  if (!query) return null;
  return `https://maps.google.com/maps?q=${encodeURIComponent(query)}&z=15&output=embed`;
}

/** Validates a hex color like #1a2b3c or #abc. */
export function isHexColor(value: string): boolean {
  return /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(value.trim());
}

/**
 * Trusted map-embed origins. Arbitrary HTTPS iframe URLs are rejected: only
 * the explicit Google Maps embed endpoints may be framed.
 */
const TRUSTED_EMBED_ORIGINS = new Set(["https://www.google.com", "https://maps.google.com"]);
export function isTrustedMapEmbed(raw: string): boolean {
  try {
    const url = new URL(raw);
    if (!TRUSTED_EMBED_ORIGINS.has(url.origin)) return false;
    if (url.pathname.startsWith("/maps/embed")) return true;
    return url.origin === "https://maps.google.com" && url.pathname === "/maps" && url.searchParams.get("output") === "embed";
  } catch {
    return false;
  }
}

/**
 * Image URL policy: strictly validated root-relative local paths or HTTPS
 * hosts on the shared allowlist (src/lib/poc/image-hosts.ts). The default
 * host set is resolved from the live server environment, so
 * POC_IMAGE_HOST_ALLOWLIST and R2_PUBLIC_BASE_URL apply at runtime exactly
 * as they do in the CSP. Local paths reject protocol-relative (//), backslash
 * (/\host, which browsers normalize to a protocol-relative URL), control
 * characters, and anything else that could normalize into an external URL.
 */
export function isAllowedImageUrl(raw: string, hosts: readonly string[] = getRuntimeImageHosts()): boolean {
  if (raw.startsWith("/")) {
    // Root-relative local path only: no protocol-relative, no backslash
    // variants, no control characters that could smuggle a URL.
    if (raw.startsWith("//") || raw.includes("\\")) return false;
    if (/[\u0000-\u001f\u007f]/.test(raw)) return false;
    return true;
  }
  try {
    const url = new URL(raw);
    return url.protocol === "https:" && hosts.includes(url.hostname.toLowerCase());
  } catch {
    return false;
  }
}
